# Generated by Django 2.2 on 2019-12-26 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sb_db_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='calificacion',
            options={'verbose_name': 'Calificación', 'verbose_name_plural': 'Calificaciones'},
        ),
        migrations.RenameField(
            model_name='autor',
            old_name='naionalidad_autor',
            new_name='nacionalidad_autor',
        ),
    ]
